[package]
name = "xime-setup"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "GPL-3.0"
repository.workspace = true

[dependencies]
xime-setup-lib.workspace = true
iced = { version = "0.14", default-features = false, features = [
    "tokio",
    "wgpu",
    "tiny-skia",
    "image",
    "svg",
    "x11",
    "wayland",
] }
anyhow = "1.0"
tracing.workspace = true
nix = { version = "0.31.3", features = ["fs"] }
zbus = "5"
