[package]
name = "xime-setup"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "GPL-3.0"
repository.workspace = true

[dependencies]
xime-setup-lib.workspace = true
gpui = { git = "https://github.com/zed-industries/zed", rev = "4605a0f8dc09461747fee50b987da5e7dd1d76f5" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "4605a0f8dc09461747fee50b987da5e7dd1d76f5", features = ["wayland"] }
anyhow = "1.0"
tracing.workspace = true
nix = { version = "0.31.3", features = ["fs"] }
zbus = "5"
