[package]
name = "xime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/ximeiorg/xime-wayland"
description = "Xime - A Wayland input method for Chinese (Wubi)"

[dependencies]
xime-daemon = { path = "../xime-daemon" }
xime-launcher = { path = "../xime-launcher" }
xime-setup = { path = "../xime-setup" }

[package.metadata.deb]
maintainer = "Kor1 <kingzcheung@gmail.com>"
copyright = "2026, Kor1"
license-file = ["../../LICENSE", "0"]
extended-description = """\
Xime (曦码) is a pure Rust implementation of a Chinese input method 
for Linux Wayland, using Rime engine and self-drawn UI."""
depends = "librime1 (>= 1.8), libxkbcommon0 (>= 1.0)"
section = "utils"
priority = "optional"
assets = [
    ["target/release/xime-daemon", "usr/bin/", "755"],
    ["target/release/xime-launcher", "usr/bin/", "755"],
    ["target/release/xime-setup", "usr/bin/", "755"],
    ["../../resources/xime.yaml", "usr/share/xime/", "644"],
    ["../../resources/dbus/org.xime.Xime.service", "usr/share/dbus-1/services/", "644"],
    ["../../resources/applications/xime-launcher.desktop", "usr/share/applications/", "644"],
    ["../../resources/applications/xime-setup.desktop", "usr/share/applications/", "644"],
    ["../../resources/icons/48x48/apps/xime.png", "usr/share/icons/hicolor/48x48/apps/", "644"],
    ["../../resources/icons/64x64/apps/xime.png", "usr/share/icons/hicolor/64x64/apps/", "644"],
    ["../../resources/icons/128x128/apps/xime.png", "usr/share/icons/hicolor/128x128/apps/", "644"],
    ["../../resources/icons/256x256/apps/xime.png", "usr/share/icons/hicolor/256x256/apps/", "644"],
    ["../../resources/icons/512x512/apps/xime.png", "usr/share/icons/hicolor/512x512/apps/", "644"],
    ["../../rime-wubi/*.yaml", "usr/share/xime/rime-data/", "644"],
    ["../../rime-wubi/lua/*.lua", "usr/share/xime/rime-data/lua/", "644"],
]
recommends = "rime-data-wubi"