[package]
name = "xime-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
xime-config.workspace = true
xime-wayland.workspace = true
xime-xkb.workspace = true
xime-ui.workspace = true
xime-tray.workspace = true
xime-server.workspace = true
librime.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_yaml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
zbus = "5"
nix = { version = "0.31.3", features = ["fs", "mman"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }