[package]
name = "xime-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
xime-wayland.workspace = true
xime-xkb.workspace = true
xime-ui.workspace = true
xime-tray.workspace = true
librime.workspace = true
thiserror.workspace = true
anyhow.workspace = true
zbus = "5"
nix = { version = "0.29", features = ["fs", "mman"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"